name: Run Robot Framework Tests

# Define quando o workflow será executado
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Define o sistema operacional para executar o job
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Clonar o repositório
      - name: Check out code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ajuste para a versão do Python que você usa

      # Passo 3: Instalar as dependências
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Passo 4: Executar os testes do Robot Framework
      - name: Run Robot Framework Tests
        run: |
          source venv/bin/activate
          robot -d results Specs/

      # Passo 5: Fazer upload dos resultados dos testes como artefatos
      - name: Upload Robot Framework Results
        uses: actions/upload-artifact@v3
        with:
          name: robot-results
          path: results/
